#!/bin/sh
# shell script to prepend i3status with more stuff

i3status | while :

paused=$(dunstctl is-paused)
mute=""

if [ "${paused}" = "true" ]; then
    mute="❌ |"
fi

audio_icon=$(case "$(pactl info | rg "Default Sink" | cut -d ":" -f 2 | xargs)" in
    "alsa_output.pci-0000_0c_00.6.analog-stereo") echo "🔊" ;;
    "alsa_output.pci-0000_0c_00.1.hdmi-stereo") echo "🖥️" ;;
    "alsa_output.usb-Audio-Technica_ATR_USB_microphone-00.analog-stereo") echo "🎧" ;;
    *) echo "🔇" ;;
esac)

kolide=$(jq -r 'if .icon == "triangle-exclamation" then " ⚠️ " + (.tooltip | capture("(?<d>In [0-9]+ Days?)") | .d) else "" end' /var/kolide-k2/k2device.kolide.com/menu.json 2>/dev/null)
fleet=$(/home/adam/.dotfiles/linux/fleet-status.sh | jq -r 'if .status == "green" then "✅" else "☠️" end')
do
  read line
  echo "${mute} ${line} |${kolide} ${fleet} ${audio_icon}" || exit 1
done
