#!/bin/sh
# shell script to prepend i3status with more stuff

i3status | while :

mail=$(/home/adam/bin/mail-count.sh)

paused=$(dunstctl is-paused)
mute=""

if [ "${paused}" = "true" ]; then
    mute="❌ |"
fi

do
  read line
  echo "${mute} ✉ ${mail} | ${line}" || exit 1
done
