#!/bin/sh

# shellcheck source=/dev/null
. ~/.dotfiles/linux/mail-query.sh

mail=$(mu find \
          --sortfield=date \
          --reverse \
          --fields='f; s; l; i' \
          "${query:?}" 2>/dev/null)
selection=$(echo "${mail}" | rofi -fullscreen -kb-custom-1 'Alt+c' -kb-custom-2 'Alt+v' -dpi 1 -dmenu -p "Preview message:")
rofi_code=$?
file_path=$(echo "${selection}" | cut -d ";" -f 3)

select_style() {
    file=$(mailpreview-cli "${file_path}" "${1}")
    file_code=$?
    browser=$(printf "Firefox\nqutebrowser" | rofi -dpi 1 -dmenu -p "Browser: ")

    if [ "${file_code}" -eq 0 ]; then
      if [ "${browser}" = "Firefox" ]; then
          firefox --new-tab "file://${file}"
      fi

      if [ "${browser}" = "qutebrowser" ]; then
          qutebrowser "file://${file}"
      fi
    fi
}

case ${rofi_code} in
    11)
        echo "${file_path}" | xclip -selection clipboard;;
    10)
        id=$(echo "${selection}" \
                 | cut -d ";" -f 4 \
                 | tr -d '[:space:]')
        link="mu4e:msgid:${id}"
        emacsclient -e "(org-link-open-from-string \"${link}\")";;
    0)
        format=$(printf "text/plain\ntext/html" | rofi -dpi 1 -dmenu -p "Format:")
        select_style "${format}";;
    *)
        exit 0;
esac
