#!/bin/sh

# shellcheck source=/dev/null
. ~/.dotfiles/linux/mail-query.sh

mail=$(mu find \
          --sortfield=date \
          --reverse \
          --fields='f; s; l; i' \
          "${query:?}" 2>/dev/null)
selection=$(echo "$mail" | rofi -fullscreen -kb-custom-1 'Alt+c' -dpi 1 -dmenu -p "Preview message:")
rofi_code=$?

if [ $rofi_code -eq 10 ]; then
  id=$(echo "$selection" \
           | cut -d ";" -f 4 \
           | tr -d '[:space:]')
  link="mu4e:msgid:$id"
  emacsclient -e "(org-link-open-from-string \"$link\")"
elif [ $rofi_code -eq 0 ]; then
  file_path=$(echo "$selection" | cut -d ";" -f 3)
  file=$(mailpreview-cli "$file_path")

  firefox --new-tab "file://$file"
else
  exit 0
fi;
