#!/bin/bash

alias l='ls -lhGa'
alias lsd='ls -l | grep "^d"'
alias server='python -m SimpleHTTPServer'
alias restart='source ~/.zshrc'
alias h='fc -l 1 | fzf'
alias c='clear'
alias zipAll='for i in */; do zip -r "${i%/}.zip" "$i"; done'
alias attach="tmux attach-session -t "
alias tls="tmux ls "
alias thelp="tmux lscm"
alias showfiles="defaults write com.apple.finder AppleShowAllFiles YES && killall Finder"
alias hidefiles="defaults write com.apple.finder AppleShowAllFiles NO && killall Finder"
alias ss='svn status'
alias sr='svn revert '
alias su='svn update'
alias sdiff='svn diff '
alias wtp='lsof -i ' #show processes running on a certain port
alias gre='git rebase origin/master'
alias gpm='git pull origin master'
alias glist='alias | grep "git" | cut -c 7-'
alias github="open \`git remote -v | grep github.com | grep fetch | head -1 | field 2 | sed 's/git:/http:/g'\`"
alias assume='git update-index --assume-unchanged'
alias unassume='git update-index --no-assume-unchanged'
alias assumed="!git ls-files -v | grep ^h | cut -c 3-"
alias gdiff='nix-shell -p difftastic --run "GIT_EXTERNAL_DIFF=difft git diff"'
alias glog='git log --format='\''%Cgreen%h%Creset %C(cyan)%an%Creset - %s'\'' --graph'
alias gs='git status '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias who='git shortlog -n -s --no-merges'
alias fbase='git fetch && git rebase origin/master'
alias cleanup='remote prune origin && git gc && git clean -dfx && git stash clear'
alias v='/usr/local/bin/vim '
alias lnpm='PATH=$(npm bin):$PATH'
alias e='emacsclient -q -t -c '
alias dired='emacsclient -e "(dired default-directory)" -c -t'
alias ssh-pass='ssh -o PreferredAuthentications=password '
alias _copy='xclip -selection clipboard'
alias _paste='xclip -selection clipboard -o'
alias dsh='docker exec -it '
alias redirects="curl -LSs -D - -o /dev/null -w 'Final URL: %{url_effective} \nNumber of Redirects: %{num_redirects} ' "
alias mpd-cloud="ssh -NTf mpd-cloud"
alias music="ncmpcpp -h ${NAS_IP} -p 6601"
alias shcheck="shellcheck -o all "
alias alpine="qemu-system-x86_64 \
    -enable-kvm \
    -m 2048 \
    -cpu host \
    -nic user,hostfwd=tcp::9000-:22,hostfwd=tcp::2000-:2000,hostfwd=tcp::3500-:3500\
    -drive file=/home/asimpson/VMs/alpine.qcow2,media=disk,if=virtio \
    -display none"
alias reset-audio="killall zoom && pulseaudio -k"
alias email="e --eval \"(mu4e)\""
alias gf="cd ~/Projects/grafana"
alias gfe="cd ~/Projects/grafana-enterprise"
alias dt="cd ~/Projects/deployment_tools"
alias k="kubectl "
