#!/bin/bash
#All my custom BASH aliases
#[misc-start]
alias l='ls -Gla'
alias lsd='ls -l | grep "^d"'
alias phpmamp='/Applications/MAMP/bin/php/php5.4.4/bin/php'
alias pubkey='more ~/.ssh/id_rsa.pub | pbcopy | echo '\''=> Public key copied to pasteboard.'\'''
alias server='open http://localhost:8000 && python -m SimpleHTTPServer'
alias restart_apache='/Applications/MAMP/bin/apache2/bin/apachectl restart'
alias r='source ~/.bash_profile'
alias g='grunt '
alias restart='source ~/.bash_profile'
alias rebuild='/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user'
#[misc-end]
#Pulled from https://github.com/livando/dotfiles/blob/master/bash/aliases

#[git-start]
alias glist='alias | grep "git" | cut -c 7-'
alias glog='git log --format='\''%Cgreen%h%Creset %C(cyan)%an%Creset - %s'\'' --graph'
alias hp='git push heroku master'
alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gca='git commit -a -m'
alias gd='git diff'
alias go='git checkout '
alias gl='git pull --rebase'
alias gk='gitk --all&'
alias gx='gitx --all'
alias gpb='git publish-branch'
alias blist='git branch -l'
alias stash='git stash'
alias switch='git checkout'
alias who='git shortlog -n -s --no-merges'
alias fbase='git fetch origin && git rebase origin/master'
alias cleanup='remote prune origin && git gc && git clean -dfx && git stash clear'
#[git-end]

alias h='history'
alias c='clear'

alias psd='open -a /Applications/Adobe\ Photoshop\ CS6/Adobe\ Photoshop\ CS6.app'