#!/bin/bash
#All my custom BASH aliases

alias glog='git log --format='\''%Cgreen%h%Creset %C(cyan)%an%Creset - %s'\'' --graph'
alias l='ls -Gla'
alias lsd='ls -l | grep "^d"'
alias phpmamp='/Applications/MAMP/bin/php/php5.4.4/bin/php'
alias pubkey='more ~/.ssh/id_rsa.pub | pbcopy | echo '\''=> Public key copied to pasteboard.'\'''
alias server='open http://localhost:8000 && python -m SimpleHTTPServer'
alias hp='git push heroku master'
alias restart_apache='/Applications/MAMP/bin/apache2/bin/apachectl restart'
alias restart='source ~/.bash_profile'
alias ip='ifconfig | grep inet'
alias glist='alias | grep "git" | cut -c 7-'

#Pulled from https://github.com/livando/dotfiles/blob/master/bash/aliases

#[GIT]
alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias go='git checkout '
alias gl='git pull --rebase'
alias gk='gitk --all&'
alias gx='gitx --all'
alias gpb='git publish-branch'
alias blist='git branch -l'
alias stash='git stash'
alias switch='git checkout'
alias who='git shortlog -n -s --no-merges'
alias cleanup='remote prune origin && git gc && git clean -dfx && git stash clear'

alias h='history'
alias c='clear'

#[Heroku]
alias hp='git push heroku master'