#!/bin/bash
#All my custom BASH functions

# encode a given image file as base64 and output css background property to clipboard
function 64enc() {
  openssl base64 -in $1 | awk -v ext="${1#*.}" '{ str1=str1 $0 }END{ print "background:url(data:image/"ext";base64,"str1");" }'|pbcopy
  echo "$1 encoded to clipboard"
}

function muxdef {
  tmux send-keys "v" C-m;
  tmux split-window -v;
  tmux split-window -h;
  tmux send-keys "gitsh" C-m;
}

function marked {
  open -a Marked.app $@
}

# Install a grunt plugin and save to devDependencies
function gi() {
  npm install --save-dev grunt-"$@"
}

# Install a grunt-contrib plugin and save to devDependencies
function gci() {
  npm install --save-dev grunt-contrib-"$@"
}

function man {
  open dash://man:$1
}
function gfind {
  awk "/#\[$1-start\]/,/#\[$1-end\]/ { print }" ~/.dotfiles/bash/aliases
}

function grab {
  git checkout $1 -- $2
}

function filepath {
  git log -p --follow -- $1
}

function ip {
  YELLOW="\033[33m"
  IP=$(ifconfig | grep 'inet 1' | cut -c 6- | awk 'NR==2 {print $1}')
  echo -e ${YELLOW}$IP
  echo $IP | pbcopy
}

function logs {
  git log -p --grep $1
}

function move_dock {
  if [ "$1" = "left" ]; then
    defaults write com.apple.dock pinning -string start && killall Dock
  fi
  if [ "$1" = "right" ]; then
    defaults write com.apple.dock pinning -string end && killall Dock
  fi
  if [ "$1" = "middle" ]; then
    defaults write com.apple.dock pinning -string middle && killall Dock
  fi
}

function dashboard_toggle {
  if [ "$1" = "kill" ]; then
    defaults write com.apple.dashboard mcx-disabled -boolean YES && killall Dock
  fi
  if [ "$1" = "show" ]; then
    defaults write com.apple.dashboard mcx-disabled -boolean NO && killall Dock
  fi
}

function vhost {
  sudo ~/.dotfiles/osx/mamp_vh.sh $1
}

function al {
 awk "/#\[$1\]/,/#\[end\]/ { print }" ~/.dotfiles/bash/aliases | cut -c 7-
}

function hack {
  for file in /Applications/MAMP/Library/vhosts/domains/*
  do
    if [ -f "$file" ];then
     echo -e "${YELLOW}${file##/*/}${NC}"
    fi
  done
}

function hg {
  history | grep --color=auto $1
}

function nb() {
  name=$1;
  git checkout -b ${name} origin/${name};
}

alias fuck='$(thefuck $(fc -ln -1))'
